### PR TITLE
Publish browserified version

### PR DESCRIPTION
**Pull request by broerse**

### CODE REVIEW

**Comment by ptitjes** [comment]
Hi Martin.

Why do you need that ? We are now publishing the `.js` and `.min.js` as assets to each release (see for instance: https://github.com/pouchdb-community/pouchdb-authentication/releases/tag/v1.1.2).

**Comment by broerse** [comment]
@ptitjes We need it in npm to be able to upgrade to the new `pouchdb-authentication` version. 

https://github.com/martinic/ember-simple-auth-pouch/blob/master/index.js#L31

**Comment by broerse** [comment]
Until Ember fixes this we need the bower version. So we like this included just as for pouchdb itself See:

https://github.com/pouchdb-community/ember-pouch/blob/master/index.js#L23

**Comment by broerse** [comment]
Just to be clear. We don't need them in git. Just in NPM.

**Comment by broerse** [comment]
If seems there is more wring here. See:

https://github.com/pouchdb-community/pouchdb-authentication/blob/master/bower.json#L5

I think bower still works because it loads an old version. See how it should be done:

https://github.com/pouchdb/pouchdb/tree/6.4.3

**Comment by broerse** [comment]
See also:

https://github.com/pouchdb/pouchdb/blob/6.4.3/package.json#L53

**Comment by broerse** [comment]
I was updating `ember-simple-auth-pouch` when I found out. But I will not need it before Monday.

**Comment by broerse** [comment]
@ptitjes did you get my email? Your mail system thinks I am a spammer if I include a link ;-)

**Comment by ptitjes** [comment]
@broerse yeah I did. I will take some time tomorrow or the day after to make the release :)

**Comment by ptitjes** [comment]
Closed by https://github.com/pouchdb-community/pouchdb-authentication/commit/46e883e.

@broerse Sorry for the delay, here is the release:
https://github.com/pouchdb-community/pouchdb-authentication/releases/tag/v1.1.3

**Comment by broerse** [comment]
Thanks!

**Pull request closed without merging**
